---
- name: installing nginx on amazon linux
  hosts: localhost
  become: true
  gather_facts: yes
  tasks:
    - name: enable epel
      command: amazon-linux-extras enable epel
    - name: download epel
      command: yum install epel-release -y
    - name: installing nginx
      command: yum install nginx -y
    - name: copy index.html
      template: src=index.html dest=/usr/share/nginx/html/index.html     
    - name: starting nginx
      command: systemctl start nginx
  handlers:
    - name: restart nginx
      command: systemctl restart nginx    
